### ISSUE TITLE
Is RockShell only for ddev

### ISSUE THREAD

**Issue by ivangretsky** [baumrock/RockShell#1]
Good day @BernhardBaumrock !

I've tried RockShell on a test installation. `pw-download` works fine, but `pw-install` does not. I looked at the code and there is ddev mentions everywhere. Is it only supposed to work in ddev environment?

**Comment by BernhardBaumrock** [comment]
Hi @ivangretsky I'd not say it's supposed to work only on ddev but that's the most reliably solution for sure (just another advantage of using it).

> I looked at the code and there is ddev mentions everywhere.

That's mostly just default values (like ddevadmin for user and password). Nothing that states it should only work with ddev. If you provide more information than just "does not work" I can maybe help.

**Comment by ivangretsky** [comment]
I am at this step and I do not know what to put here as host to make it work)

![изображение](https://user-images.githubusercontent.com/6697626/198890183-213b2c96-749e-48de-9cd4-c08d0dadf75f.png)

**Comment by BernhardBaumrock** [comment]
Can you try the latest version? I have pushed a little change...

This is how it looks like when I enter a wrong host:
<img src=https://i.imgur.com/OtZalEi.png>

And this is how it should look like:
![image](https://user-images.githubusercontent.com/8488586/198891585-45137ffc-0be8-4018-b1db-c98ae8179804.png)

**Comment by BernhardBaumrock** [comment]
The host must be a valid hostname/URL where the installer runs. In my case that is always something like foo.ddev.site which RockShell then sends the HTTP requests to http://foo.ddev.site/install.php

Are you maybe trying to install in a subfolder?

**Comment by ivangretsky** [comment]
1. I did run `git submodule update` - hope it does the updating.
2. I assume I need to run `php rockshell pw-install` before the install. So I did.
3. Then I run `php rockshell pw-install` and input a 3rd level domain name like test.site.com
And  I get this message: `Failed to connect to localhost port 80: Connection refused for "http://localhost/test.site.com"`. The PW installer is available via derect link to that domain. It seems to add `localhost` part whatever I enter.

**Comment by BernhardBaumrock** [comment]
> I did run git submodule update - hope it does the updating.
I don't think so. As far as I understand that does only update the submodule to the reference that you provide in the master repo. So if you don't update that reference that command will not update the module. But you don't need submodules for RockShell - just copy the latest files

> I assume I need to run php rockshell pw-install before the install. So I did.
Sure, that's the purpose of the installer - to install PW.

> Then I run php rockshell pw-install and input a 3rd level domain name like test.site.com
And I get this message: Failed to connect to localhost port 80: Connection refused for "http://localhost/test.site.com". The PW installer is available via derect link to that domain. It seems to add localhost part whatever I enter.

Yeah I saw that in your previous post and was confused. I'm just using Symfonys browser tools... I don't know why it tries to connect to that url. It's likely a routing issue but that's really not my strong foot.

**Comment by BernhardBaumrock** [comment]
@ivangretsky I'll close this issue. Please reopen it if it is sill an issue.
