### ISSUE TITLE
The pw:install command leaves site/config.php with many duplicate lines.

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockShell#10]
Some sections of the site/config.php file are duplicated if PW is installed using the pw:install command.

This includes, but may not be limited to, the following settings, and their comment blocks: debug, salts, dbXyz.

**Comment by netcarver** [comment]
Hi @BernhardBaumrock. Not for at least a couple of weeks. I have a bit of a backlog at the moment.

**Comment by BernhardBaumrock** [comment]
@netcarver seems the issue is not related to RockShell but the core itself? https://github.com/processwire/processwire-issues/issues/1936

**Comment by netcarver** [comment]
Ok, thanks Bernhard, closing this one now.
