### ISSUE TITLE
Symlink command removed in 3.0?

### ISSUE THREAD

**Issue by jlahijani** [baumrock/RockShell#13]
I just updated to 3.0 and I noticed the symlink command was removed.  Is there a new practice for making it easier to call on RockShell?

**Comment by BernhardBaumrock** [comment]
Hey @jlahijani yes, I'm using an alias instead: https://www.baumrock.com/en/processwire/modules/rockshell/docs/setup/#using-ddev

**Comment by BernhardBaumrock** [comment]
I've updated the docs, thx
