### ISSUE TITLE
pw:install fails to connect to host when using DDEV custom ports

### ISSUE THREAD

**Issue by lemachinarbo** [baumrock/RockShell#17]
**Description:**

When a DDEV project is configured with custom HTTP and HTTPS ports, such as:
```yaml
router_http_port: "8080"
router_https_port: "8443"
```

the `pw:install` command fails to connect, defaulting to port 80 instead. This causes the command to fail with the message:

```
Failed to connect to xxx.ddev.site port 80 after 1 ms: Couldn't connect to server for "http://xxx.ddev.site/install.php"
```

**Expected Behavior:**

I was expecting the command to detect that the web is running on a different port (e.g., `8080` or `8443`).

**Steps to Reproduce:**

1. Configure a DDEV project with custom ports:
   ```yaml
   router_http_port: "8080"
   router_https_port: "8443"
   ```
2. Run `pw:install` in the terminal.
3. Observe the connection failure due to default port 80 being used.

**Proposed Solution:**

Update the connection check in `pw:install` to detect and prioritize custom DDEV ports ([DDEV_ROUTER_HTTP_PORT](https://ddev.readthedocs.io/en/stable/users/configuration/config/#router_https_port) and [DDEV_ROUTER_HTTPS_PORT](https://ddev.readthedocs.io/en/stable/users/configuration/config/#router_https_port)).

Here's a [PR](https://github.com/baumrock/RockShell/pull/16) if you think this solution is suitable.

**Comment by BernhardBaumrock** [comment]
Hey @lemachinarbo thank you very much for taking the time to look into it and also for explaining and documenting everything so well! I've merged your PR 💯
