### ISSUE TITLE
pw:install option ignores --url command line option

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockShell#8]
If I `ddev ssh` into the web container & cd RockShell/. Then  doing `./rock pw:install --url=location` ignores the `--url=location` argument and always installs PW to the default "processwire" path.

I fixed it locally by changing [line 319](https://github.com/baumrock/RockShell/blob/e4bed0b47b33f6a2aab72b53f7297dc7f1c3df18/App/Commands/PwInstall.php#L319) in the install command to...

```php
$value = $this->ask($label, $this->option('url') ?: 'processwire');
```

**Comment by BernhardBaumrock** [comment]
Thx, I've added your fix :)
